# Numpy Arrays

importing numpy 

In [2]:
import numpy as np

# 1.Data Types and Attributes

In [3]:
#ndarrays
array1=np.array([1,5,8,7])
array1

array([1, 5, 8, 7])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2=np.array([[1,7.0,9.2],
                [5,9,2]])

array3=np.array([[[10,12,15],
                  [10,16,52],
                  [15,5,4]],
                  [[0,12,5],
                  [10,6,7],
                  [5,2,1]]])


In [6]:
array2

array([[1. , 7. , 9.2],
       [5. , 9. , 2. ]])

In [7]:
array3

array([[[10, 12, 15],
        [10, 16, 52],
        [15,  5,  4]],

       [[ 0, 12,  5],
        [10,  6,  7],
        [ 5,  2,  1]]])

In [8]:
array1.shape

(4,)

In [9]:
array2.shape

(2, 3)

In [10]:
array3.shape

(2, 3, 3)

In [11]:
array1.ndim,array2.ndim,array3.ndim

(1, 2, 3)

In [12]:
array1.size

4

In [13]:
array2

array([[1. , 7. , 9.2],
       [5. , 9. , 2. ]])

In [14]:
#Creating a dataFrame using Numpy array
import pandas as pd

df=pd.DataFrame(array2)
df

0    1    2
0  1.0  7.0  9.2
1  5.0  9.0  2.0

# 2. Creating Arrays

In [15]:
sample_array=np.array([1,2,3])
sample_array


array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones=np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [22]:
zeros=np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array=np.arange(0,10,2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array=np.random.randint(0,10,size=(3,5))

In [36]:
random_array

array([[6, 2, 8, 8, 7],
       [4, 7, 7, 9, 4],
       [9, 2, 9, 3, 3]])

In [37]:
random_array.size

15

In [39]:
random_array.shape

(3, 5)

In [40]:
random_array2=np.random.random((5,3))

In [41]:
random_array2

array([[0.79131036, 0.70788844, 0.73121578],
       [0.99443951, 0.50371429, 0.45157148],
       [0.24773693, 0.34420781, 0.38628719],
       [0.84508093, 0.16657381, 0.67075254],
       [0.45123472, 0.24080883, 0.24897575]])

In [42]:
random_array2.shape,random_array2.size

((5, 3), 15)

In [45]:
random_array3=np.random.random((5,3))

In [46]:
random_array3

array([[0.36932583, 0.01300361, 0.30847102],
       [0.73417338, 0.16130842, 0.55834808],
       [0.66700971, 0.08052399, 0.19783245],
       [0.35718722, 0.89610722, 0.68200762],
       [0.86990392, 0.06918976, 0.53333789]])

In [50]:
np.random.seed(seed=99999)
random_array4=np.random.randint(10,size=(5,3))

In [51]:
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [52]:
np.random.seed(7)
random_array5=np.random.random((5,3))

In [53]:
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# 3. Viewing arrays and matrices

In [54]:
np.unique(random_array4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [56]:
array1

array([1, 5, 8, 7])

In [57]:
array2

array([[1. , 7. , 9.2],
       [5. , 9. , 2. ]])

In [58]:
array3

array([[[10, 12, 15],
        [10, 16, 52],
        [15,  5,  4]],

       [[ 0, 12,  5],
        [10,  6,  7],
        [ 5,  2,  1]]])

In [59]:
array1[0]

1

In [60]:
array2.shape

(2, 3)

In [61]:
array3[0]

array([[10, 12, 15],
       [10, 16, 52],
       [15,  5,  4]])

In [62]:
array3

array([[[10, 12, 15],
        [10, 16, 52],
        [15,  5,  4]],

       [[ 0, 12,  5],
        [10,  6,  7],
        [ 5,  2,  1]]])

In [63]:
array3[1]

array([[ 0, 12,  5],
       [10,  6,  7],
       [ 5,  2,  1]])

In [64]:
array3.shape

(2, 3, 3)

In [65]:
array3[:2,:2,:2]

array([[[10, 12],
        [10, 16]],

       [[ 0, 12],
        [10,  6]]])

In [66]:
array4=np.random.randint(10,size=(2,3,4,5))

In [67]:
array4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [70]:
array4.shape,array4.ndim

((2, 3, 4, 5), 4)

# 4.Manupulating and Comparing Arrays 

Arithmetic

In [71]:
array1

array([1, 5, 8, 7])

In [77]:
ones=np.ones(4)

In [78]:
ones

array([1., 1., 1., 1.])

In [79]:
array1 + ones

array([2., 6., 9., 8.])

In [80]:
array1-ones

array([0., 4., 7., 6.])

In [81]:
array1*ones

array([1., 5., 8., 7.])

In [82]:
array1*array2

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [94]:
re=array1.reshape(2,2)
re

array([[1, 5],
       [8, 7]])

In [95]:
array2

array([[1. , 7. , 9.2],
       [5. , 9. , 2. ]])

In [96]:
re.shape

(2, 2)

In [98]:
a1=np.array([1,2,3])

In [99]:
a1*array2

array([[ 1. , 14. , 27.6],
       [ 5. , 18. ,  6. ]])

In [101]:
ones

array([1., 1., 1., 1.])

In [102]:
ones.shape

(4,)

In [103]:
np.square(array2)

array([[ 1.  , 49.  , 84.64],
       [25.  , 81.  ,  4.  ]])

In [104]:
#Taking Square by method 2(**)
array2**2

array([[ 1.  , 49.  , 84.64],
       [25.  , 81.  ,  4.  ]])

In [107]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [108]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])